package com.cnksi.kconf.controller.vo;

import com.cnksi.kcore.web.KWebQueryVO;
import com.cnksi.kcore.web.api.KQuery;
import com.cnksi.kcore.web.api.KQueryParam;

/**
 * Generated by JFinal.
 */
@KQuery(select = "SELECT * ", from = " from k_department  ")
public class DepartmentQuery extends KWebQueryVO {
    @KQueryParam(colName = "dname", op = "like")
    private String dname;

    public DepartmentQuery(){
        addFilter("  enabled = 0");
    }
    public String getDname() {
        return dname;
    }

    public void setDname(String dname) {
        this.dname = dname;
    }
}
