package com.cnksi.kconf.controller.vo;

import com.cnksi.kcore.web.KWebQueryVO;
import com.cnksi.kcore.web.api.KQuery;
import com.cnksi.kcore.web.api.KQueryParam;

/**
 * Generated by JFinal.
 */
@KQuery(select = "SELECT u.*,r.rname,d.dname,d.jcdwid,d.id as dpid,d.type as depttype,pd.dname as pidDept",
from = "FROM k_user u ", 
join = " LEFT JOIN k_department d ON u.dept_id =d.id LEFT JOIN k_user_role ur on ur.user_id = u.id LEFT JOIN k_role r on r.id = ur.role_id" +
		" left join k_department pd on d.pid = pd.id ",orderBy = "u.sort")
public class UserQuery extends KWebQueryVO {
	/**
	 * 姓名
	 */
	@KQueryParam(colName = "u.uname", op = "like")
	private String uname;

	/**
	 * 手机号
	 */
	@KQueryParam(colName = "u.tel", op = "like")
	private String tel;

	/**
	 * 所属部门
	 */
	@KQueryParam(colName = "u.dept_id", op = "=")
	private String deptid;

	/**
	 * 用户账号
	 */
	@KQueryParam(colName = "u.uaccount", op = "like")
	private String uaccount;

	public UserQuery() {
		addFilter("u.enabled", "=", "0");
	}

	public String getDeptid() {
		return deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getUaccount() {
		return uaccount;
	}

	public void setUaccount(String uaccount) {
		this.uaccount = uaccount;
	}

}
