package com.cnksi.kconf.controller;

import com.jfinal.config.Routes;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configRoute(Routes me) {
 *    _RouteKit.mapping(me); 
 * 	} 
 </pre>
 */
public class _RouteKit {

	public static void mapping(Routes me) { me.add("/app/menu",  MenuController.class,"/menu"); }
}

