package com.cnksi.kconf.model;

import java.util.List;

import com.cnksi.kcore.jfinal.model.BaseModel;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LookupType extends BaseModel<LookupType> {

	public static final LookupType me = new LookupType();

	@SuppressWarnings("rawtypes")
	@Override
	protected Class getCls() {
		return this.getClass();
	}

	public List<Record> findJson() {
		String sql = "select ltid as id ,tname as name from " + tableName + " where enabled=0 order by sort asc ";
		return Db.find(sql);
	}

}
