package com.cnksi.kconf.model;

import com.cnksi.kcore.jfinal.model.BaseModel;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import java.util.List;
/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenu extends BaseModel<RoleMenu> {

	public static final RoleMenu me = new RoleMenu();


	@SuppressWarnings("rawtypes") 
 	@Override 
 	  protected Class getCls() {
		return this.getClass();
	}
	
	
	
	
	/**
	 * 根据角色id查询角色的所有菜单
	 * @param roleid
	 * @return
	 */
	public List<Record> findMenuIdsByRoleId(String propertity, String roleid){
		String sql =  String.format("select * from %s where %s = ? and enabled = 0", tableName, propertity);
		
		return Db.find(sql, roleid);
	}
	
	/**
	 * 根据角色id删除角色的所有菜单
	 * @param propertity
	 * @param roleid
	 */
	public void deleteByRoleid(String propertity, String roleid){
//		String sql = String.format("delete from %s where %s = ? ", tableName, propertity);
		String sql = String.format("update %s set enabled = 1 where %s = ? ", tableName, propertity);
		
		Db.update(sql, roleid);
	}
}
