package com.cnksi.kconf.model;

import java.util.List;

import com.cnksi.kcore.jfinal.model.BaseModel;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleAuthority extends BaseModel<RoleAuthority> {

	public static final RoleAuthority me = new RoleAuthority();


	@SuppressWarnings("rawtypes") 
 	@Override 
 	  protected Class getCls() {
		return this.getClass();
	}
	
	/**
	 * 根据角色id查询角色的所有权限
	 * @param roleid
	 * @return
	 */
	public List<Record> findAuthorityIdsByRoleId(String propertity, String roleid){
		String sql =  String.format("select * from %s where %s = ? and enabled = 0", tableName, propertity);
		
		return Db.find(sql, roleid);
	}
	
	/**
	 * 根据角色id删除角色的所有权限
	 * @param propertity
	 * @param roleid
	 */
	public void deleteByRoleid(String propertity, String roleid){
//		String sql = String.format("delete from %s where %s = ? ", tableName, propertity);
		String sql = String.format("update %s set enabled = 1 where %s = ? ", tableName, propertity);
		
		Db.update(sql, roleid);
	}
}
